// Code generated by protoc-gen-go. DO NOT EDIT.
// source: got-kings.proto

package gotKings

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Type int32

const (
	Type_ATTACK  Type = 0
	Type_BARTER  Type = 1
	Type_CONVERT Type = 2
	Type_PILLAGE Type = 3
	Type_MARRY   Type = 4
)

var Type_name = map[int32]string{
	0: "ATTACK",
	1: "BARTER",
	2: "CONVERT",
	3: "PILLAGE",
	4: "MARRY",
}

var Type_value = map[string]int32{
	"ATTACK":  0,
	"BARTER":  1,
	"CONVERT": 2,
	"PILLAGE": 3,
	"MARRY":   4,
}

func (x Type) String() string {
	return proto.EnumName(Type_name, int32(x))
}

func (Type) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_75b8e3a63bbbe99f, []int{0}
}

type BoolResult struct {
	Result               bool     `protobuf:"varint,1,opt,name=Result,proto3" json:"Result,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *BoolResult) Reset()         { *m = BoolResult{} }
func (m *BoolResult) String() string { return proto.CompactTextString(m) }
func (*BoolResult) ProtoMessage()    {}
func (*BoolResult) Descriptor() ([]byte, []int) {
	return fileDescriptor_75b8e3a63bbbe99f, []int{0}
}

func (m *BoolResult) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BoolResult.Unmarshal(m, b)
}
func (m *BoolResult) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BoolResult.Marshal(b, m, deterministic)
}
func (m *BoolResult) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BoolResult.Merge(m, src)
}
func (m *BoolResult) XXX_Size() int {
	return xxx_messageInfo_BoolResult.Size(m)
}
func (m *BoolResult) XXX_DiscardUnknown() {
	xxx_messageInfo_BoolResult.DiscardUnknown(m)
}

var xxx_messageInfo_BoolResult proto.InternalMessageInfo

func (m *BoolResult) GetResult() bool {
	if m != nil {
		return m.Result
	}
	return false
}

type CharacterReq struct {
	Name                 string   `protobuf:"bytes,1,opt,name=Name,proto3" json:"Name,omitempty"`
	House                string   `protobuf:"bytes,2,opt,name=House,proto3" json:"House,omitempty"`
	Keywords             []string `protobuf:"bytes,3,rep,name=Keywords,proto3" json:"Keywords,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CharacterReq) Reset()         { *m = CharacterReq{} }
func (m *CharacterReq) String() string { return proto.CompactTextString(m) }
func (*CharacterReq) ProtoMessage()    {}
func (*CharacterReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_75b8e3a63bbbe99f, []int{1}
}

func (m *CharacterReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CharacterReq.Unmarshal(m, b)
}
func (m *CharacterReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CharacterReq.Marshal(b, m, deterministic)
}
func (m *CharacterReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CharacterReq.Merge(m, src)
}
func (m *CharacterReq) XXX_Size() int {
	return xxx_messageInfo_CharacterReq.Size(m)
}
func (m *CharacterReq) XXX_DiscardUnknown() {
	xxx_messageInfo_CharacterReq.DiscardUnknown(m)
}

var xxx_messageInfo_CharacterReq proto.InternalMessageInfo

func (m *CharacterReq) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *CharacterReq) GetHouse() string {
	if m != nil {
		return m.House
	}
	return ""
}

func (m *CharacterReq) GetKeywords() []string {
	if m != nil {
		return m.Keywords
	}
	return nil
}

type CharacterInfo struct {
	FullName             string   `protobuf:"bytes,1,opt,name=FullName,proto3" json:"FullName,omitempty"`
	Description          string   `protobuf:"bytes,2,opt,name=Description,proto3" json:"Description,omitempty"`
	ConqueredLand        []string `protobuf:"bytes,3,rep,name=ConqueredLand,proto3" json:"ConqueredLand,omitempty"`
	Alliances            []string `protobuf:"bytes,4,rep,name=Alliances,proto3" json:"Alliances,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CharacterInfo) Reset()         { *m = CharacterInfo{} }
func (m *CharacterInfo) String() string { return proto.CompactTextString(m) }
func (*CharacterInfo) ProtoMessage()    {}
func (*CharacterInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_75b8e3a63bbbe99f, []int{2}
}

func (m *CharacterInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CharacterInfo.Unmarshal(m, b)
}
func (m *CharacterInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CharacterInfo.Marshal(b, m, deterministic)
}
func (m *CharacterInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CharacterInfo.Merge(m, src)
}
func (m *CharacterInfo) XXX_Size() int {
	return xxx_messageInfo_CharacterInfo.Size(m)
}
func (m *CharacterInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_CharacterInfo.DiscardUnknown(m)
}

var xxx_messageInfo_CharacterInfo proto.InternalMessageInfo

func (m *CharacterInfo) GetFullName() string {
	if m != nil {
		return m.FullName
	}
	return ""
}

func (m *CharacterInfo) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

func (m *CharacterInfo) GetConqueredLand() []string {
	if m != nil {
		return m.ConqueredLand
	}
	return nil
}

func (m *CharacterInfo) GetAlliances() []string {
	if m != nil {
		return m.Alliances
	}
	return nil
}

type Scenario struct {
	ScenarioType         Type     `protobuf:"varint,1,opt,name=ScenarioType,proto3,enum=janus.gameOfThronesData.gotKings.Type" json:"ScenarioType,omitempty"`
	Participants         []string `protobuf:"bytes,2,rep,name=Participants,proto3" json:"Participants,omitempty"`
	Aggressor            int32    `protobuf:"varint,3,opt,name=Aggressor,proto3" json:"Aggressor,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Scenario) Reset()         { *m = Scenario{} }
func (m *Scenario) String() string { return proto.CompactTextString(m) }
func (*Scenario) ProtoMessage()    {}
func (*Scenario) Descriptor() ([]byte, []int) {
	return fileDescriptor_75b8e3a63bbbe99f, []int{3}
}

func (m *Scenario) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Scenario.Unmarshal(m, b)
}
func (m *Scenario) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Scenario.Marshal(b, m, deterministic)
}
func (m *Scenario) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Scenario.Merge(m, src)
}
func (m *Scenario) XXX_Size() int {
	return xxx_messageInfo_Scenario.Size(m)
}
func (m *Scenario) XXX_DiscardUnknown() {
	xxx_messageInfo_Scenario.DiscardUnknown(m)
}

var xxx_messageInfo_Scenario proto.InternalMessageInfo

func (m *Scenario) GetScenarioType() Type {
	if m != nil {
		return m.ScenarioType
	}
	return Type_ATTACK
}

func (m *Scenario) GetParticipants() []string {
	if m != nil {
		return m.Participants
	}
	return nil
}

func (m *Scenario) GetAggressor() int32 {
	if m != nil {
		return m.Aggressor
	}
	return 0
}

type ScenarioResult struct {
	Results              []*GOTResult `protobuf:"bytes,1,rep,name=Results,proto3" json:"Results,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *ScenarioResult) Reset()         { *m = ScenarioResult{} }
func (m *ScenarioResult) String() string { return proto.CompactTextString(m) }
func (*ScenarioResult) ProtoMessage()    {}
func (*ScenarioResult) Descriptor() ([]byte, []int) {
	return fileDescriptor_75b8e3a63bbbe99f, []int{4}
}

func (m *ScenarioResult) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ScenarioResult.Unmarshal(m, b)
}
func (m *ScenarioResult) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ScenarioResult.Marshal(b, m, deterministic)
}
func (m *ScenarioResult) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ScenarioResult.Merge(m, src)
}
func (m *ScenarioResult) XXX_Size() int {
	return xxx_messageInfo_ScenarioResult.Size(m)
}
func (m *ScenarioResult) XXX_DiscardUnknown() {
	xxx_messageInfo_ScenarioResult.DiscardUnknown(m)
}

var xxx_messageInfo_ScenarioResult proto.InternalMessageInfo

func (m *ScenarioResult) GetResults() []*GOTResult {
	if m != nil {
		return m.Results
	}
	return nil
}

type GOTResult struct {
	Winner               int32    `protobuf:"varint,1,opt,name=Winner,proto3" json:"Winner,omitempty"`
	ResultDescription    string   `protobuf:"bytes,2,opt,name=ResultDescription,proto3" json:"ResultDescription,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GOTResult) Reset()         { *m = GOTResult{} }
func (m *GOTResult) String() string { return proto.CompactTextString(m) }
func (*GOTResult) ProtoMessage()    {}
func (*GOTResult) Descriptor() ([]byte, []int) {
	return fileDescriptor_75b8e3a63bbbe99f, []int{5}
}

func (m *GOTResult) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GOTResult.Unmarshal(m, b)
}
func (m *GOTResult) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GOTResult.Marshal(b, m, deterministic)
}
func (m *GOTResult) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GOTResult.Merge(m, src)
}
func (m *GOTResult) XXX_Size() int {
	return xxx_messageInfo_GOTResult.Size(m)
}
func (m *GOTResult) XXX_DiscardUnknown() {
	xxx_messageInfo_GOTResult.DiscardUnknown(m)
}

var xxx_messageInfo_GOTResult proto.InternalMessageInfo

func (m *GOTResult) GetWinner() int32 {
	if m != nil {
		return m.Winner
	}
	return 0
}

func (m *GOTResult) GetResultDescription() string {
	if m != nil {
		return m.ResultDescription
	}
	return ""
}

func init() {
	proto.RegisterEnum("janus.gameOfThronesData.gotKings.Type", Type_name, Type_value)
	proto.RegisterType((*BoolResult)(nil), "janus.gameOfThronesData.gotKings.BoolResult")
	proto.RegisterType((*CharacterReq)(nil), "janus.gameOfThronesData.gotKings.CharacterReq")
	proto.RegisterType((*CharacterInfo)(nil), "janus.gameOfThronesData.gotKings.CharacterInfo")
	proto.RegisterType((*Scenario)(nil), "janus.gameOfThronesData.gotKings.Scenario")
	proto.RegisterType((*ScenarioResult)(nil), "janus.gameOfThronesData.gotKings.ScenarioResult")
	proto.RegisterType((*GOTResult)(nil), "janus.gameOfThronesData.gotKings.GOTResult")
}

func init() { proto.RegisterFile("got-kings.proto", fileDescriptor_75b8e3a63bbbe99f) }

var fileDescriptor_75b8e3a63bbbe99f = []byte{
	// 514 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x94, 0x54, 0x51, 0x6f, 0xda, 0x3c,
	0x14, 0xfd, 0x42, 0x80, 0x86, 0x0b, 0xed, 0xc7, 0xac, 0x69, 0x8a, 0xd0, 0x1e, 0xa2, 0xa8, 0x9a,
	0x50, 0xd7, 0x65, 0x13, 0xfb, 0x05, 0x21, 0x65, 0xb4, 0x83, 0x96, 0xce, 0x8b, 0x56, 0x6d, 0x6f,
	0x1e, 0xb8, 0xc1, 0x6b, 0x6a, 0x53, 0xdb, 0x68, 0xe2, 0x67, 0xec, 0x6d, 0xff, 0x65, 0x7f, 0x6e,
	0x8a, 0x13, 0x28, 0xa8, 0x0f, 0x19, 0x6f, 0xf7, 0x1c, 0x9f, 0x63, 0x9f, 0xcb, 0xbd, 0x04, 0xfe,
	0x4f, 0x84, 0x7e, 0x73, 0xc7, 0x78, 0xa2, 0x82, 0x85, 0x14, 0x5a, 0x20, 0xef, 0x07, 0xe1, 0x4b,
	0x15, 0x24, 0xe4, 0x9e, 0x4e, 0x6e, 0xe3, 0xb9, 0x14, 0x9c, 0xaa, 0x33, 0xa2, 0x49, 0x90, 0x08,
	0x3d, 0xca, 0x74, 0xfe, 0x31, 0x40, 0x5f, 0x88, 0x14, 0x53, 0xb5, 0x4c, 0x35, 0x7a, 0x01, 0xf5,
	0xbc, 0x72, 0x2d, 0xcf, 0xea, 0x3a, 0xb8, 0x40, 0x7e, 0x0c, 0xad, 0x68, 0x4e, 0x24, 0x99, 0x6a,
	0x2a, 0x31, 0x7d, 0x40, 0x08, 0xaa, 0x57, 0xe4, 0x9e, 0x1a, 0x55, 0x03, 0x9b, 0x1a, 0x3d, 0x87,
	0xda, 0xb9, 0x58, 0x2a, 0xea, 0x56, 0x0c, 0x99, 0x03, 0xd4, 0x01, 0x67, 0x44, 0x57, 0x3f, 0x85,
	0x9c, 0x29, 0xd7, 0xf6, 0xec, 0x6e, 0x03, 0x6f, 0xb0, 0xff, 0xcb, 0x82, 0xc3, 0xcd, 0xb5, 0x17,
	0xfc, 0x56, 0x64, 0xea, 0x0f, 0xcb, 0x34, 0xdd, 0xba, 0x7b, 0x83, 0x91, 0x07, 0xcd, 0x33, 0xaa,
	0xa6, 0x92, 0x2d, 0x34, 0x13, 0xbc, 0x78, 0x65, 0x9b, 0x42, 0xc7, 0x70, 0x18, 0x09, 0xfe, 0xb0,
	0xa4, 0x92, 0xce, 0xc6, 0x84, 0xcf, 0x8a, 0x07, 0x77, 0x49, 0xf4, 0x12, 0x1a, 0x61, 0x9a, 0x32,
	0xc2, 0xa7, 0x54, 0xb9, 0x55, 0xa3, 0x78, 0x24, 0xfc, 0xdf, 0x16, 0x38, 0x9f, 0xa7, 0x94, 0x13,
	0xc9, 0x04, 0xfa, 0x08, 0xad, 0x75, 0x1d, 0xaf, 0x16, 0x79, 0xa4, 0xa3, 0xde, 0xab, 0xa0, 0xec,
	0x57, 0x0d, 0x32, 0x35, 0xde, 0xf1, 0x22, 0x1f, 0x5a, 0xd7, 0x44, 0x6a, 0x36, 0x65, 0x0b, 0xc2,
	0xb5, 0x72, 0x2b, 0xe6, 0xe5, 0x1d, 0xce, 0x44, 0x4b, 0x12, 0x49, 0x95, 0x12, 0xd2, 0xb5, 0x3d,
	0xab, 0x5b, 0xc3, 0x8f, 0x84, 0x7f, 0x03, 0x47, 0xeb, 0x1b, 0x8b, 0x71, 0x0d, 0xe0, 0x20, 0xaf,
	0x94, 0x6b, 0x79, 0x76, 0xb7, 0xd9, 0x7b, 0x5d, 0x1e, 0x6d, 0x38, 0x89, 0x73, 0x0f, 0x5e, 0x7b,
	0xfd, 0x4f, 0xd0, 0xd8, 0xb0, 0xd9, 0x0a, 0xdc, 0x30, 0xce, 0xa9, 0x34, 0xdd, 0xd6, 0x70, 0x81,
	0xd0, 0x29, 0x3c, 0xcb, 0x15, 0x4f, 0x87, 0xf0, 0xf4, 0xe0, 0x24, 0x82, 0xaa, 0xe9, 0x1a, 0xa0,
	0x1e, 0xc6, 0x71, 0x18, 0x8d, 0xda, 0xff, 0x65, 0x75, 0x3f, 0xc4, 0xf1, 0x00, 0xb7, 0x2d, 0xd4,
	0x84, 0x83, 0x68, 0x72, 0xf5, 0x65, 0x80, 0xe3, 0x76, 0x25, 0x03, 0xd7, 0x17, 0xe3, 0x71, 0x38,
	0x1c, 0xb4, 0x6d, 0xd4, 0x80, 0xda, 0x65, 0x88, 0xf1, 0xd7, 0x76, 0xb5, 0xf7, 0xc7, 0x06, 0x67,
	0x58, 0xe4, 0x46, 0x02, 0x5a, 0x43, 0xaa, 0x37, 0xeb, 0x82, 0x82, 0xf2, 0x56, 0xb7, 0x57, 0xb6,
	0xf3, 0x76, 0x0f, 0xbd, 0xd9, 0x45, 0x06, 0xce, 0x25, 0xb9, 0xa3, 0xd9, 0x11, 0xda, 0xd7, 0xdc,
	0x39, 0x2d, 0x37, 0x6c, 0xfd, 0xed, 0x28, 0x40, 0x94, 0x12, 0x35, 0xcf, 0x3b, 0x3d, 0x29, 0xf7,
	0xae, 0xf7, 0xa0, 0xb3, 0xcf, 0xc0, 0x51, 0x0a, 0x30, 0xa4, 0xfa, 0x9c, 0x29, 0x2d, 0xe4, 0x0a,
	0xed, 0x15, 0xb1, 0xf3, 0xee, 0xdf, 0x43, 0xe5, 0x8e, 0x3e, 0x7c, 0x73, 0xd6, 0x47, 0xdf, 0xeb,
	0xe6, 0x73, 0xf4, 0xfe, 0x6f, 0x00, 0x00, 0x00, 0xff, 0xff, 0x41, 0x49, 0x6b, 0x92, 0xa1, 0x04,
	0x00, 0x00,
}
